Has Real Estate/Controllers/AdminOperationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace Has_Real_Estate.Controllers
{
    [Authorize(Roles=ClsRoles.roleAdmin)]

    public class AdminOperationsController : Controller
    {
        private readonly IAdminOperationsRepo _adminrepo;
        public AdminOperationsController(IAdminOperationsRepo adminrepo)
        {
            _adminrepo = adminrepo;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GetAllEstates() 
        { 
           var es= _adminrepo.GetAllEstates();
            return View(es);
        }

        public async Task<IActionResult> ToggleApprovementStatus(int estateId) 
        {
            await _adminrepo.ToggleApprovementStatus(estateId);
            return RedirectToAction("GetAllEstates");
        
        }

    }
}

Has Real Estate/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Has_Real_Estate.Controllers
{
    [Authorize(Roles =ClsRoles.roleAdmin)]
    public class RolesController : Controller
    {
        private readonly UserManager<AppUser> _user;
        private readonly RoleManager<IdentityRole> _roles;
        public RolesController(UserManager<AppUser> user, RoleManager<IdentityRole> roles)
        {
            _user = user;
            _roles = roles;
        }
        public async Task<IActionResult> Index()
        {
            var _users = await _user.Users.ToListAsync();
            return View(_users);
        }
        public async Task<IActionResult> addRoles(string userId)
        {
            var user = await _user.FindByIdAsync(userId);
            var userRoles = await _user.GetRolesAsync(user);

            var allRoles = await _roles.Roles.ToListAsync();
            if (allRoles != null)
            {
                var roleList = allRoles.Select(r => new roleViewModel()
                {
                    roleId = r.Id,
                    roleName = r.Name,
                    useRole = userRoles.Any(x => x == r.Name)
                });
                ViewBag.userName = user.UserName;
                ViewBag.userId = userId;
                return View(roleList);
            }
            else
                return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> addRoles(string userId, string jsonRoles)
        {
            var user = await _user.FindByIdAsync(userId);

            List<roleViewModel> myRoles =
                JsonConvert.DeserializeObject<List<roleViewModel>>(jsonRoles);

            if (user != null)
            {
                var userRoles = await _user.GetRolesAsync(user);

                foreach (var role in myRoles)
                {
                    if (userRoles.Any(x => x == role.roleName.Trim()) && !role.useRole)
                    {
                        await _user.RemoveFromRoleAsync(user, role.roleName.Trim());
                    }

                    if (!userRoles.Any(x => x == role.roleName.Trim()) && role.useRole)
                    {
                        await _user.AddToRoleAsync(user, role.roleName.Trim());
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            else
                return NotFound();
        }
    }
}

Has Real Estate/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    @* BootStrap *@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <!--DtataTable-->
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.8/css/dataTables.bootstrap5.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/3.0.2/css/responsive.bootstrap5.css" />

    <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.min.css" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />


    <link rel="stylesheet" href="~/EstateWebsite.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/adminstyle.css" />

    <link rel="stylesheet" href="~/css/bootstrap.min(3).css" />

</head>
<body>
    <div class="main-contaier">

        @* side nav bar *@
        <nav class="sidenav list-group ">

            <a class="navigation-link   " asp-controller="Home" asp-action="Index">Back To Home</a>
            <a class="navigation-link   " asp-controller="AdminOperations" asp-action="Index">    Dashboard  </a>
            <a class="navigation-link   " asp-controller="Roles" asp-action="Index">User Roles</a>
            <a class="navigation-link   " asp-area="" asp-controller="AdminOperations" asp-action="GetAllEstates">Manage Properties  </a>
             
            <a href="/Reports/TopFiveSellingBooks" class="navigation-link  "><i class="bi bi-bar-chart"></i> Top Salling Items</a>

        </nav>
        @*  upper nav bar *@
        <div class="right-panel">
            <nav class="nav-bar">
                <div class="nav-heading">Welcome @User.Identity?.Name</div>
                <div class="nav-actions">
                    <a href="/Identity/Account/Manage/Index" class="navigation-link"><i class="bi bi-gear"></i> Manage account</a>
                    <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                        <button type="submit" class="navigation-link">
                            <i class="bi bi-box-arrow-left"></i> Logout
                        </button>
                    </form>
                </div>
            </nav>
            <div class="content container">
                @RenderBody()
            </div>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap core JS-->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    <!--DtataTable-->
    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.js "></script>
    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.bootstrap5.js"></script>
    <script src="https://cdn.datatables.net/responsive/3.0.2/js/dataTables.responsive.js "></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Has Real Estate/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]  EstateWebsite</title>

    <!-- Favicon -->
    <link rel="icon" href="img/favicon.ico">
    <!--Other-->
    <link rel="stylesheet"  href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.min.css" />
    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    
    <link rel="stylesheet" href="~/theme/css/google web fonts.css" />

    <!-- Icon Font Stylesheet --> 
    <link rel="stylesheet" href="~/theme/fontawesome-free-6.5.2-web/css/all.css" />
    <link rel="stylesheet" href="~/theme/fontawesome-free-6.5.2-web/css/all.min.css" />

    <!-- Libraries Stylesheet -->      
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EstateWebsite.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/theme/lib/animate/animate.min.css" />
    <link rel="stylesheet" href="~/theme/lib/owlcarousel/assets/owl.carousel.min.css"  />

    <!-- Customized Bootstrap Stylesheet -->  
    <link rel="stylesheet" href="~/theme/css/bootstrap.min.css" />
    <!-- Template Stylesheet -->  
    <link rel ="stylesheet" href="~/theme/css/style.css" />
    
  
</head>
<body>
    
    <header>
        <!-- Navbar Start -->
        <div class="container-fluid nav-bar bg-transparent">
            <nav class="navbar navbar-expand-lg bg-white navbar-light py-0 px-4">
                <a class="navbar-brand d-flex align-items-center text-center" asp-controller="Home" asp-action="Index">
                    <div class="icon p-2 me-2">
                        <img class="img-fluid" src="~/theme/img/icon-deal.png" alt="Icon" style="width: 30px; height: 30px;">
                    </div>
                    <h1 class="m-0 text-primary">Has Real Estate</h1>
                </a>
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto">
                        <a asp-controller="Home" asp-action="Index" class="nav-item nav-link active">Home</a> 
                        <a asp-action="Explore" asp-controller="Estate" class="nav-item nav-link">Explore </a> 
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Manage</a>
                            <div class="dropdown-menu rounded-0 m-0">
                                <a asp-action="Create" asp-controller="Estate" class="dropdown-item">Sell Or Rent Your Property</a> 
                                <a asp-action="Index" asp-controller="Estate" class="dropdown-item">Manage Your Properties</a> 
                                <a asp-action="GetSavedProperty" asp-controller="Estate" class="dropdown-item">Saved </a>
                            </div>

                        </div>  
                        @if (User.IsInRole(ClsRoles.roleAdmin))
                        {
                            <a class="nav-link" asp-controller="AdminOperations" asp-action="Index">Admin Dashboard</a>
                        }
                        
                    </div>
                     
                    <partial name="_LoginPartial" />
                </div>
            </nav>
        </div>
        <!-- Navbar End -->
    </header>
    <div >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">Get In Touch</h5>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">Quick Links</h5>
                    <a class="btn btn-link text-white-50" href="">About Us</a>
                    <a class="btn btn-link text-white-50" href="">Contact Us</a>
                    <a class="btn btn-link text-white-50" href="">Our Services</a>
                    <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                    <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">Photo Gallery</h5>
                    <div class="row g-2 pt-2">
                        <div class="col-4">
                            <img class="img-fluid rounded bg-light p-1" src="img/property-1.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid rounded bg-light p-1" src="img/property-2.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid rounded bg-light p-1" src="img/property-3.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid rounded bg-light p-1" src="img/property-4.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid rounded bg-light p-1" src="img/property-5.jpg" alt="">
                        </div>
                        <div class="col-4">
                            <img class="img-fluid rounded bg-light p-1" src="img/property-6.jpg" alt="">
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">Newsletter</h5>
                    <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                        <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                        <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.

                        <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                        Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                    </div>
                    <div class="col-md-6 text-center text-md-end">
                        <div class="footer-menu">
                            <a href="">Home</a>
                            <a href="">Cookies</a>
                            <a href="">Help</a>
                            <a href="">FQAs</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->
    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EstateWebsite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@

    @*  <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script> *@

    <!-- Template Libraries -->
    <script src="~/theme/js/jquery-3.4.1.min.js"></script>
    <script src="~/theme/js/bootstrap.bundle.min.js"></script>
    <script src="~/theme/lib/wow/wow.min.js"></script>
    <script src="~/theme/lib/easing/easing.min.js"></script>
    <script src="~/theme/lib/waypoints/waypoints.min.js"></script>
    <script src="~/theme/lib/owlcarousel/owl.carousel.min.js"></script>

    <!--  Javascript -->
    <script src="~/theme/js/main.js"></script> 
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!--Others-->
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
     
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>